spring:
  application:
    name: Online Ankete i Glasanja
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pollhub}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: -1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false

jwt:
  secret: ${JWT_SECRET:ZGV2ZWxvcG1lbnQtcG9sbGh1Yi1qd3Qtc2VjcmV0LWtleS1tdXN0LWJlLWF0LWxlYXN0LTMyLWJ5dGVzLWxvbmc=}
  expiration: ${JWT_EXPIRATION:86400000}
